In [27]:
import numpy as np

class MLP:
    def __init__(self):
        self.input_size = 2
        self.hidden_size = 4
        self.output_size = 1
        
        self.w1 = np.random.random((self.input_size, self.hidden_size))
        self.w2 = np.random.random((self.hidden_size, self.output_size))
        self.b1 = np.array([np.random.random() for TO in range(self.hidden_size)])
        self.b2 = np.array([np.random.random() for TO in range(self.output_size)])
        
        self.ITERS = 100
        self.LR = 0.1
        self.alpha = 0.01

    def predict(self, x, return_hidden_output=False):
        hidden_input = self.forward(x, self.w1, self.b1)
        hidden_output = self.relu(hidden_input)
        if return_hidden_output:
            return hidden_output
        output_input = self.forward(hidden_output, self.w2, self.b2)
        output = self.relu(output_input)
        return output

    def forward(self, l1, w, b):
        l2 = np.dot(l1, w) + b
        return l2

    def train(self, X, Y):
        for _ in range(self.ITERS):
            for x, y in zip(X, Y):
                self.backward(x, y)

    def backward(self, x, y):
        hidden_output = self.predict(x, return_hidden_output=True)
        pred = self.predict(x)
        #print(pred)
        
        #loss = (pred-y)**2
        
        output_error = 2 * (pred - y) 
        #* self.relu(pred)
        hidden_error = np.dot(output_error, self.w2.T)
        #print(hidden_error)
        
        w2_grad = hidden_output.T * output_error
        h_grad = np.dot(hidden_output, hidden_error.T)
        w1_grad = np.outer(x, h_grad)
        #* self.relu(hidden_output)
        #print(w1_grad)
        #print(hidden_output)
        
        self.update_weights(self.w2, self.b2, w2_grad)
        self.update_weights(self.w1, self.b1, w1_grad)

    def update_weights(self, w, b, error):
        #error = error[0]
        #print(error)
        #dot = np.outer(error, w)
        #dot = np.atleast_1d(dot.squeeze())
        #print(w, np.outer(error, w))
        #print(w.shape, (np.outer(error,w)*self.LR).shape)
        #w -= self.LR * np.outer(error, w)
        #print(w.shape[0], w.shape[1])
        #print(w)
        print(error)
        for FROM in range(w.shape[0]):
            for TO in range(w.shape[1]):
                w[FROM][TO] -= self.LR * error[FROM]
                #print(b, TO)
                b[TO] -= self.LR * error[FROM]
            #print(i)

    def relu(self, x):
        return np.where(x > 0, x, 0)

X = np.array([
    [0, 0],
    [1, 0],
    [0, 1],
    [1, 1]
])
Y = np.array([[0], [1], [1], [0]])  # Corrected Y values to be a NumPy array

model = MLP()
model.train(X, Y)

# Test the trained model
a = model.predict([1, 0])
print("Prediction:", a)


[1.4779386  1.62539865 3.38397007 0.26852012]
[[0.]
 [0.]]


<ipython-input-27-4716c017946f>:71: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  w[FROM][TO] -= self.LR * error[FROM]
<ipython-input-27-4716c017946f>:73: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  b[TO] -= self.LR * error[FROM]


[0.10736061 0.20186534 0.14615376 0.04947254]
[[0.14786098]
 [0.        ]]
[0.43170063 1.05495575 1.03059812 0.7790961 ]
[[0.        ]
 [1.02104279]]
[1.08745552 3.44615138 1.92797551 1.77665023]
[[1.87450481]
 [1.87450481]]
[0. 0. 0. 0.]
[[0.]
 [0.]]
[-0.07689056 -1.36641725 -0.60622705 -0.        ]
[[0.12358073]
 [0.        ]]
[-0.         -1.25472714 -1.18978852 -0.5192719 ]
[[-0.        ]
 [-0.20482719]]
[0. 0. 0. 0.]
[[0.]
 [0.]]
[0. 0. 0. 0.]
[[0.]
 [0.]]
[-0.06842371 -1.3579504  -0.5977602  -0.        ]
[[-0.34210741]
 [-0.        ]]
[-0.         -1.39454117 -1.3300896  -0.66460197]
[[-0.        ]
 [-0.87975328]]
[0.35710469 3.34206479 1.42079361 1.22928951]
[[2.37157235]
 [2.37157235]]
[0. 0. 0. 0.]
[[0.]
 [0.]]
[-0.         -0.24780061 -0.         -0.        ]
[[-0.03375047]
 [-0.        ]]
[-0.         -0.3407875  -0.27584887 -0.        ]
[[-0.        ]
 [-0.10781043]]
[0. 0. 0. 0.]
[[0.]
 [0.]]
[0. 0. 0. 0.]
[[0.]
 [0.]]
[-0.         -0.28286288 -0.         -0.        ]
[[-0